
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
/**

/**
 *
 * @author BENMOUSSA
 */
public class EtudiantAcc extends javax.swing.JFrame implements MouseMotionListener,MouseListener{

    /**
     * Creates new form EtudiantAcc
     */
    public EtudiantAcc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/student_male.png")));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		//khess
        	}
        });
        jPanel2.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENUE  "+connexionEtudiant.p.get(0).getNom().toUpperCase()+"  "+connexionEtudiant.p.get(0).getPrenom());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("–");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        
        label = new JLabel();
        label.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		LabelMouseClicked(e);
        	}
        });
        label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        label.setText("<");
        label.setForeground(Color.WHITE);
        label.setFont(new Font("Tahoma", Font.BOLD, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addGap(40)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 457, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        			.addGap(26)
        			.addComponent(jLabel2)
        			.addGap(18))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(25)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(label, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3)
        				.addComponent(jLabel1))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(Color.GRAY);
        Resultat pf=new Resultat();
        /**/
        try 
		{
		//1
		Class.forName("com.mysql.jdbc.Driver");
		//2
		Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/projet1112","root",""); 
		Statement pr=cn.createStatement();
		ResultSet rs=pr.executeQuery("SELECT * FROM resultat where idusers='"+connexionEtudiant.p.get(0).getId()+"'");//permet de recuperer les donnees dune table
		
		while(rs.next())
		{
			pf.setIdresultat(rs.getInt(1));
			pf.setValide(rs.getInt(4));
			compteur++;
		}
		
		} 
		catch (Exception e) 
		{		
			e.printStackTrace();
		}
        
        System.out.println(pf.getValide());
        
        /**/
        
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        
        if(compteur<2)
        {
        
        if(pf.getValide()!=1)
        {
        jLabel4.setText("Passer l'examen");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        
        }
        else
        {
        	jLabel4.setText("Vous avez deja passer l'examen");
        	jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        	 jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                 public void mouseClicked(java.awt.event.MouseEvent evt) {
                	 JOptionPane.showMessageDialog(null, "L'Examen Est Bloque");
                 }
             });
        }
        
        }
        else
        {
        	jLabel4.setText("Vous avez passe la limite de passage ");
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Consulter mes Resultats");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }	
        });
        if(compteur<2)
        {
        if(pf.getValide()!=1) {
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/advance.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        }
        else
        {
        	 jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/valide.png"))); // NOI18N
             jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
             jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                 public void mouseClicked(java.awt.event.MouseEvent evt) {
                	 JOptionPane.showMessageDialog(null, "L'Examen Est Bloque");
                 }
             });
        	
        }
        }else {
        	jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fermer.png"))); // NOI18N
            jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
        
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cons.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(46)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabel4))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel7)
        					.addGap(18)
        					.addComponent(jLabel5)))
        			.addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(97)
        					.addComponent(jLabel4))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(82)
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)))
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
        					.addComponent(jLabel7)
        					.addGap(149))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(91)
        					.addComponent(jLabel5)
        					.addContainerGap())))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );
        this.setIconImage(new ImageIcon(this.getClass().getResource("class.png")).getImage()); 
        getContentPane().setLayout(layout);
        addMouseMotionListener(this);
        addMouseListener(this);
        pack();
    }// </editor-fold>                        

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
            System.exit(0);
    }                                    

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
             this.setState(JFrame.ICONIFIED);
    }                                    

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {                                     
 	   
		   try {
	             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                 if ("Nimbus".equals(info.getName())) {
	                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                     break;
	                 }
	             }
	         } catch (ClassNotFoundException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         } catch (InstantiationException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         } catch (IllegalAccessException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         }
	        
	         java.awt.EventQueue.invokeLater(new Runnable() {
	             public void run() {
	                 new Exam().setVisible(true);
	             }
	         });
    }                                    

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }
    private void LabelMouseClicked(java.awt.event.MouseEvent evt) {                                     
    	 int rep=JOptionPane.showConfirmDialog(null, "vous voulez vraiment se deconnecter","se deconnecter",JOptionPane.YES_NO_OPTION);
         if(rep==JOptionPane.OK_OPTION)
         {
             this .hide();
             try {
 	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
 	                if ("Nimbus".equals(info.getName())) {
 	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
 	                    break;
 	                }
 	            }
 	        } catch (ClassNotFoundException ex) {
 	            java.util.logging.Logger.getLogger(connexionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 	        } catch (InstantiationException ex) {
 	            java.util.logging.Logger.getLogger(connexionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 	        } catch (IllegalAccessException ex) {
 	            java.util.logging.Logger.getLogger(connexionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
 	            java.util.logging.Logger.getLogger(connexionEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 	        }
 	       
 	        java.awt.EventQueue.invokeLater(new Runnable() {
 	            public void run() {
 	                new connexionEtudiant().setVisible(true);
 	            }
 	        });
 	        
         }
    } 

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
 	   
		   try {
	             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                 if ("Nimbus".equals(info.getName())) {
	                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                     break;
	                 }
	             }
	         } catch (ClassNotFoundException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         } catch (InstantiationException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         } catch (IllegalAccessException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	             java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	         }
	        
	         java.awt.EventQueue.invokeLater(new Runnable() {
	             public void run() {
	                 new Exam().setVisible(true);
	             }
	         });   
	this.hide();         
    }                                    

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {                                     
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationResultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultationResultat().setVisible(true);
            }
        });
        this.hide();
    }                                    

    

    // Variables declaration - do not modify
    private int compteur=0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JLabel label;
    // End of variables declaration 
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		initX = e.getX();
		initY = e.getY();
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}
	int initX = 0;
	int initY=0;
	@Override
	public void mouseDragged(MouseEvent e) {
int deplacementX =  e.getX()-initX;
		
		int deplacementY =  e.getY()-initY;		
	         this.setLocation(this.getLocation().x+deplacementX, this.getLocation().y+deplacementY);
		
	}

	@Override
	public void mouseMoved(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}                  
}
